packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.38.0
  '@fastify/cookie': ^11.0.2
  '@fastify/cors': ^11.1.0
  '@fastify/helmet': ^13.0.2
  '@fastify/rate-limit': ^10.3.0
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/jetbrains-mono': ^5.2.8
  '@fontsource-variable/source-serif-4': ^5.2.9
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-use-controllable-state': ^1.2.2
  '@t3-oss/env-core': ^0.13.8
  '@tabler/icons-react': ^3.35.0
  '@tailwindcss/vite': ^4.1.15
  '@tanstack/devtools-vite': ^0.3.10
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/eslint-plugin-router': ^1.133.19
  '@tanstack/react-devtools': ^0.7.8
  '@tanstack/react-form': ^1.23.7
  '@tanstack/react-form-devtools': ^0.1.7
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.133.21
  '@tanstack/react-router-devtools': ^1.133.21
  '@tanstack/react-store': ^0.8.0
  '@tanstack/router-plugin': ^1.133.21
  '@tanstack/zod-adapter': ^1.133.36
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  '@types/eslint-plugin-jsx-a11y': ^6.10.1
  '@types/node': ^24.9.1
  '@vitejs/plugin-legacy': ^7.2.1
  '@vitejs/plugin-react-swc': ^3.11.0
  better-auth: ^1.3.34
  browser-sync: ^3.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  cross-env: ^10.1.0
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  drizzle-seed: ^0.3.1
  drizzle-zod: ^0.8.3
  eslint: ^9.38.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-tsdoc: ^0.4.0
  eslint-plugin-turbo: ^2.5.8
  eslint-plugin-unicorn: ^59.0.1
  fastify: ^5.6.1
  globals: ^16.4.0
  lucide-react: ^0.525.0
  motion: ^12.23.24
  mysql2: ^3.15.2
  next-themes: ^0.4.6
  pino-pretty: ^13.1.2
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react-phone-number-input: ^3.4.12
  sonner: ^2.0.7
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.15
  tsup: ^8.5.0
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  url-join: ^5.0.0
  vaul: ^1.1.2
  vite: ^7.1.11
  vite-plugin-browser-sync: ^4.0.0
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.12

catalogs:
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0

onlyBuiltDependencies:
  - esbuild
