/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPublicContactRouteImport } from './routes/_app/_public/contact'
import { Route as AppPublicAboutRouteImport } from './routes/_app/_public/about'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicContactRoute = AppPublicContactRouteImport.update({
  id: '/_public/contact',
  path: '/contact',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicAboutRoute = AppPublicAboutRouteImport.update({
  id: '/_public/about',
  path: '/about',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppPublicAboutRoute
  '/contact': typeof AppPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppPublicAboutRoute
  '/contact': typeof AppPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_public/about': typeof AppPublicAboutRoute
  '/_app/_public/contact': typeof AppPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/_public/about'
    | '/_app/_public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/contact': {
      id: '/_app/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppPublicContactRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/about': {
      id: '/_app/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppPublicAboutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPublicAboutRoute: typeof AppPublicAboutRoute
  AppPublicContactRoute: typeof AppPublicContactRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPublicAboutRoute: AppPublicAboutRoute,
  AppPublicContactRoute: AppPublicContactRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
